#!/bin/bash
#Accession list
input="accessions.txt"

#Functions
filedownload () {
  echo Cleaning files for: $var;
  unlink $var
  echo Downloading $var;
  wget "${url//\"/}"
}

#Download metadata/check if file exists/download file if not exists/check integrity/download again if corrupted
while read -r line
do
  echo "$line"
  ffq "$line" > "$line".json
  elen=`jq '.. | select(.ftp?).ftp' "$line".json | jq length`
  echo FTP Files: "$elen"
  elen=$((--elen))
  while [ $elen -ge 0 ]
  do
    md5=`jq '.[].files.ftp[$i].md5' --argjson i $elen "$line".json`; echo MD5: "$md5"
    url=`jq '.[].files.ftp[$i].url' --argjson i $elen "$line".json`; echo URL: "$url"
    bspl=`jq '.[].sample' "$line".json`; echo BioSample: "$bspl"
    for var in `echo "${url//\"/}" | rev | cut -d "/" -f1 | rev`
    do
      if test -f "$var"
      then
          echo "$var exists"
      else
          echo "Downloading $var";
          filedownload
      fi
      if [[ `md5sum "$var"` == *"${md5//\"/}"* ]]
      then
        echo "File not corrupted."
      else
        echo "File corrupted."
        while [[ `md5sum "$var"` != *"${md5//\"/}"* ]]
        do
          filedownload
          done
      fi
    done
    elen=$((--elen))
    done
done < "$input"

for filejs in `find ./ -name "*?.json"`
  do
  echo "$filejs"
  bspl=`jq '.[].sample' "$filejs"`; echo BioSample: "$bspl"
  filnm=`jq '.[].accession' "$filejs"`; echo Acession: "$filnm"
  smr=`esearch -db biosample -query $bspl | esummary -mode json`
  splnm=`echo "$smr" | jq '.. | select(.title?).title'`
  splnm=${splnm^^}
  attb=`jq '.. | select(.sampledata?).sampledata' <<< "$smr"`
  attb=${attb##*<Attributes>}
  attb=${attb%</Attributes>*}
  echo $attb
  attnms=$(echo $attb | grep -oP '(?<=<Attribute ).*?(?=</Attribute>)' | tr '\n' '^')
  elemn=$(echo $attb | grep -oP '(?<=attribute_name=\\").*?(?=\\")' | wc -l)
  echo "$elemn" Attributes
  while [ $elemn -gt 0 ]
    do
    attln=$(echo $attnms | cut -d "^" -f$elemn)
    attln=${attln##*attribute_name=\\\"}
    attnm=$(echo $attln | cut -d "\\" -f1)
    attvar=${attln##*>}
    echo Attribute Name: $attnm
    echo Attribute Var: $attvar
    elemn=$((--elemn))
    done
  done




#s='<Attribute attribute_name=\"ENA first public\">2016-11-29</Attribute> <Attribute attribute_name=\"ENA last update\">2016-06-27</Attribute>'
#grep -oP '(?<=from=).*?(?=,)' <<< "$s"
#smr=$(cat "samplesmr.txt")
#esearch -db biosample -query $bspl | esummary -mode json
#esearch -db bioproject -query 'PRJEB14614' | esummary -mode json
