#!/bin/bash
#Accession list
input="accessions.txt"

#Download metadata/check if file exists/download file if not exists
while read -r line
do
  echo "$line"
  ffq "$line" > "$line".json
  elen=`jq '.. | select(.ftp?).ftp' "$line".json | jq length`
  echo FTP Files: "$elen"
  elen=$((--elen))
  while [ $elen -ge 0 ]
  do
    md5=`jq '.[].files.ftp[$i].md5' --argjson i $elen "$line".json`; echo MD5: "$md5"
    url=`jq '.[].files.ftp[$i].url' --argjson i $elen "$line".json`; echo URL: "$url"
    for var in `echo "${url//\"/}" | rev | cut -d "/" -f1 | rev`
    do
      if test -f "$var"
      then
          echo "$var exists"
      else
          echo "Downloading $var";
          wget "${url//\"/}"
      fi
      md5sum=`md5sum "$var"`
      echo MD5SUM: $md5sum
      if [[ "$md5sum" == *"${md5//\"/}"* ]]
      then
        echo "File not corrupted."
      else
        echo "File corrupted"
      fi
    done
    elen=$((--elen))
    done
done < "$input"
