#!/bin/bash
#Accession list
input="accessions.txt"

#Download metadata/check if file exists/download file if not exists
while read -r line
do
  echo "$line"
  ffq "$line" > "$line".json
  jq '.. | select(.url?).url' ERR1474664.json | grep "ftp" | while read -r url; do echo "${url//\"/}";
  #ads="ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR147/004/ERR1474664/ERR1474664_1.fastq.gz"
  for var in `echo "${url//\"/}" | rev | cut -d "/" -f1 | rev`
    do
      echo "$var"
      if test -f "$var"
      then
          echo "$var exists"
      else
          echo "Downloading $var";
          wget "${url//\"/}"
      fi
      done
  done
done < "$input"
